version: '3.8'

services:
  depotbde:
    build: .
    container_name: depotbde
    env_file:
      - .env
    ports:
      - "3007:3007"
    networks:
      - depotbde-network
    volumes:
      - uploads_data:/app/uploads
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_APP_URL=https://depotbde.hipp-dev.fr
      - PORT=3007
      - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
      - DATABASE_URL=${DATABASE_URL}
      - DIRECT_URL=${DIRECT_URL}
      # Variables pour l'authentification simplifée
      - AUTH_USERNAME=admin
      - AUTH_PASSWORD=admin123

networks:
  depotbde-network:

volumes:
  uploads_data:
    driver: local 