version: '3.8'

services:
  bde:
    build: .
    container_name: bde
    restart: always
    ports:
      - "3007:3007"
    networks:
      - bde-network
    volumes:
      - uploads_data:/app/uploads
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_APP_URL=https://bde.hipp-dev.fr
      - PORT=3007


networks:
  bde-network:

volumes:
  uploads_data:
    driver: local 