version: '3.8'

services:
  depotbde:
    build: .
    container_name: depotbde
    restart: always
    ports:
      - "3007:3007"
    networks:
      - depotbde-network
    volumes:
      - uploads_data:/app/uploads
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_APP_URL=https://depotbde.hipp-dev.fr
      - PORT=3007


networks:
  depotbde-network:

volumes:
  uploads_data:
    driver: local 